<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_bracket_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VBracketSearchinterface extends \app\models\Bracket
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_bracket_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
