<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_contact_group_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VContactGroupSearchinterface extends \app\models\ContactGroup
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_contact_group_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
