<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_data_transfer_type_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VDataTransferTypeSearchinterface extends \app\models\DataTransferType
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_data_transfer_type_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
