<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_db_table_type_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VDbTableTypeSearchinterface extends \app\models\DbTableType
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_db_table_type_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
