<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_db_table_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VDbTableSearchinterface extends \app\models\DbTable
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_db_table_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }

	// { ... phabricator-task: T59
    public function attributeLabels() {
		
		$addionalLabels = array('databaseInfoFromLocation' => Yii::t('app', 'Database'));
		return array_merge(parent::attributeLabels(), $addionalLabels);
    }
    // ...}
}
