<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_glossary_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VGlossarySearchinterface extends \app\models\Glossary
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_glossary_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
