<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_import_stage_db_table_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VImportStageDbTableSearchinterface extends \app\models\ImportStageDbTable
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_import_stage_db_table_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
