<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_keyfigure_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VKeyfigureSearchinterface extends \app\models\Keyfigure
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_keyfigure_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
