<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_map_object_2_object_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VMapObject2ObjectSearchinterface extends \app\models\MapObject2Object
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_map_object_2_object_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
