<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_object_comment_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VObjectCommentSearchinterface extends \app\models\Objectcomment
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_object_comment_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
