<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_object_depends_on_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VObjectDependsOnSearchinterface extends \app\models\ObjectDependsOn
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_object_depends_on_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
