<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_sourcesystem_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VSourcesystemSearchinterface extends \app\models\Sourcesystem
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_sourcesystem_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
