<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_tool_SearchInterface".
 * (Generated by meta#grid Python helper tools).
 */
class VToolSearchinterface extends \app\models\Tool
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'v_tool_SearchInterface';
    }
    public static function primaryKey()
    {
        return array('id');
    }
}
