CREATE TABLE keyfigure (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 1 REFERENCES object_type (id),
fk_project_id INTEGER DEFAULT NULL REFERENCES project (id),
name TEXT(250) DEFAULT NULL,
description TEXT(4000) DEFAULT NULL,
formula TEXT(4000) DEFAULT NULL
);

CREATE TABLE object_type (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
name TEXT(250) DEFAULT NULL
);

CREATE TABLE client (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL
);

CREATE TABLE project (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_client_id INTEGER NOT NULL  DEFAULT NULL REFERENCES client (id),
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL
);

CREATE TABLE sourcesystem (
id INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 2 REFERENCES object_type (id),
fk_project_id INTEGER DEFAULT NULL REFERENCES project (id),
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL,
fk_contact_group_id_as_supporter INTEGER DEFAULT NULL REFERENCES contact_group (id)
);

CREATE TABLE data_delivery_object (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 3 REFERENCES object_type (id),
fk_project_id INTEGER DEFAULT NULL REFERENCES project (id),
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL,
fk_tool_id INTEGER NOT NULL  DEFAULT NULL REFERENCES tool (id),
fk_data_delivery_type_id INTEGER DEFAULT NULL REFERENCES data_delivery_type (id),
fk_contact_group_id_as_data_owner INTEGER DEFAULT NULL REFERENCES contact_group (id)
);

CREATE TABLE map_object_2_object (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
ref_fk_object_id_1 INTEGER NOT NULL  DEFAULT NULL,
ref_fk_object_type_id_1 INTEGER NOT NULL  DEFAULT NULL REFERENCES object_type (id),
ref_fk_object_id_2 INTEGER DEFAULT NULL,
ref_fk_object_type_id_2 INTEGER NOT NULL  DEFAULT NULL REFERENCES object_type (id),
UNIQUE (ref_fk_object_id_1, ref_fk_object_type_id_1, ref_fk_object_id_2, ref_fk_object_type_id_2)
);

CREATE TABLE tool (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_tool_type_id INTEGER DEFAULT NULL REFERENCES tool_type (id),
tool_name TEXT(255) DEFAULT NULL,
vendor TEXT(255) DEFAULT NULL,
version TEXT(255) DEFAULT NULL,
comment TEXT(500) DEFAULT NULL
);

CREATE TABLE object_depends_on (
id INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
ref_fk_object_id_parent INTEGER DEFAULT NULL,
ref_fk_object_type_id_parent INTEGER DEFAULT NULL,
ref_fk_object_id_child INTEGER DEFAULT NULL,
ref_fk_object_type_id_child INTEGER DEFAULT NULL
);

CREATE TABLE attribute (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 9 REFERENCES object_type (id),
fk_project_id INTEGER NOT NULL  DEFAULT NULL REFERENCES project (id),
name TEXT(250) DEFAULT NULL,
description TEXT(4000) DEFAULT NULL,
formula TEXT(4000) DEFAULT NULL
);

CREATE TABLE tool_type (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL
);

CREATE TABLE db_table (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 4 REFERENCES object_type (id),
fk_project_id INTEGER NOT NULL  DEFAULT NULL REFERENCES project (id),
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL,
location TEXT DEFAULT NULL,
fk_db_table_context_id INTEGER DEFAULT NULL REFERENCES db_table_context (id),
fk_db_table_type_id INTEGER DEFAULT NULL REFERENCES db_table_type (id)
);

CREATE TABLE db_table_field (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 5 REFERENCES object_type (id),
fk_project_id INTEGER NOT NULL  DEFAULT NULL REFERENCES project (id),
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL,
fk_db_table_id INTEGER DEFAULT NULL REFERENCES db_table (id),
datatype TEXT(250) DEFAULT NULL,
bulk_load_checksum TEXT(200) DEFAULT NULL
);

CREATE TABLE db_table_context (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 6 REFERENCES object_type (id),
fk_project_id INTEGER NOT NULL  DEFAULT NULL REFERENCES project (id),
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL,
prefix TEXT(100) DEFAULT NULL
);

CREATE TABLE db_database (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 11 REFERENCES object_type (id),
fk_project_id INTEGER NOT NULL  DEFAULT NULL REFERENCES project (id),
name TEXT DEFAULT NULL,
description TEXT DEFAULT NULL,
fk_tool_id INTEGER NOT NULL  DEFAULT NULL REFERENCES tool (id)
);

CREATE TABLE scheduling (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 8 REFERENCES object_type (id),
fk_project_id INTEGER NOT NULL  DEFAULT NULL REFERENCES project (id),
name TEXT DEFAULT NULL,
description TEXT DEFAULT NULL,
fk_tool_id INTEGER NOT NULL  DEFAULT NULL REFERENCES tool (id),
scheduling_series TEXT DEFAULT NULL
);

CREATE TABLE parameter (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 7 REFERENCES object_type (id),
fk_project_id INTEGER NOT NULL  DEFAULT NULL REFERENCES project (id),
name TEXT DEFAULT NULL,
description TEXT DEFAULT NULL,
is_optional INTEGER DEFAULT NULL,
default_value TEXT DEFAULT NULL,
datatype TEXT DEFAULT NULL,
range TEXT DEFAULT NULL
);

CREATE TABLE db_table_type (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
name TEXT DEFAULT NULL,
description TEXT DEFAULT NULL
);

CREATE TABLE object_comment (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 12 REFERENCES object_type (id),
ref_fk_object_id INTEGER DEFAULT NULL,
ref_fk_object_type_id INTEGER DEFAULT NULL REFERENCES object_type (id),
comment TEXT DEFAULT NULL,
created_at_datetime TEXT DEFAULT NULL
);

CREATE TABLE glossary (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 10 REFERENCES object_type (id),
fk_project_id INTEGER NOT NULL  DEFAULT NULL REFERENCES project (id),
name TEXT DEFAULT NULL,
description TEXT DEFAULT NULL
);

CREATE TABLE data_delivery_type (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL
);

CREATE TABLE data_transfer_process (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 13 REFERENCES object_type (id),
fk_project_id INTEGER NOT NULL  DEFAULT NULL REFERENCES project (id),
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL,
fk_data_transfer_type_id INTEGER DEFAULT NULL REFERENCES data_transfer_type (id)
);

CREATE TABLE data_transfer_type (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL
);

CREATE TABLE app_config (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
key TEXT DEFAULT NULL,
valueINT TEXT DEFAULT NULL,
valueSTRING TEXT DEFAULT NULL,
description TEXT DEFAULT NULL
);

CREATE TABLE contact_group (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER DEFAULT 14 REFERENCES object_type (id),
fk_client_id INTEGER NOT NULL  DEFAULT NULL REFERENCES client (id),
name TEXT DEFAULT NULL,
description TEXT DEFAULT NULL,
short_name TEXT DEFAULT NULL
);

CREATE TABLE contact (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER DEFAULT 15 REFERENCES object_type (id),
fk_contact_group_id INTEGER DEFAULT NULL REFERENCES contact_group (id),
fk_client_id INTEGER NOT NULL  DEFAULT NULL REFERENCES client (id),
givenname TEXT DEFAULT NULL,
surname TEXT DEFAULT NULL,
email TEXT DEFAULT NULL,
phone TEXT DEFAULT NULL,
mobile TEXT DEFAULT NULL,
ldap_cn TEXT DEFAULT NULL,
description TEXT DEFAULT NULL
);

CREATE TABLE bracket (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 16 REFERENCES object_type (id),
fk_project_id INTEGER DEFAULT NULL REFERENCES project (id),
name TEXT(250) DEFAULT NULL,
description TEXT(500) DEFAULT NULL,
fk_attribute_id INTEGER NULL DEFAULT NULL REFERENCES attribute (id),
fk_object_type_id_as_searchFilter INTEGER DEFAULT NULL REFERENCES object_type (id)
);

CREATE TABLE bracket_searchPattern (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
uuid TEXT DEFAULT NULL,
fk_object_type_id INTEGER NOT NULL  DEFAULT 17 REFERENCES object_type (id),
fk_bracket_id INTEGER NOT NULL REFERENCES bracket (id),
searchPattern TEXT(500) NOT NULL
);
