do
$$
declare
  l_rec record;
  l_sql text;
  l_table text;
begin
  for l_rec in select table_schema, table_name, column_name, data_type, is_nullable
               from information_schema.columns
               where column_name IN ('id','log_id') --<< adjust here
                 and table_schema = 'public' --<< adjust here
                 and data_type in ('bigint', 'integer', 'int')
                 and is_nullable = 'NO' 
                 and is_generated = 'NEVER'
                 and is_identity = 'NO' 
                 AND column_default IS NULL
                 AND table_name NOT IN ('databasechangeloglock')
  loop
    l_sql := format('alter table %I.%I alter %I add generated by default as identity', 
                     l_rec.table_schema, 
                     l_rec.table_name, 
                     l_rec.column_name);
    -- change the column to an identity column
    RAISE NOTICE 'execute sql: %', l_sql;                 
    execute l_sql;
    l_table := concat(quote_ident(l_rec.table_schema), '.', quote_ident(l_rec.table_name));
    
    -- synchronize the sequence with the max value from the table
    l_sql := format('select setval(pg_get_serial_sequence(%L, %L), max(%I)) from %I.%I', 
                    l_table, 
                    quote_ident(l_rec.column_name), 
                    l_rec.column_name, 
                    l_rec.table_schema, 
                    l_rec.table_name);
    RAISE NOTICE 'execute sql: %', l_sql;
    execute l_sql;
  end loop;
end;  
$$
;